package com.youxianji.pojo;
// Generated 2017-3-20 18:53:04 by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * YxjBuserWithdrawcashTrace generated by hbm2java
 */
public class YxjBuserWithdrawcashTrace  implements java.io.Serializable {


     private String traceId;
     private YxjBuserWithdrawcashUpper cashUpper;
     private Date operateTime;
     private String cashState;
     private AdminUser operator;
     private String remark;
	public String getTraceId() {
		return traceId;
	}
	public void setTraceId(String traceId) {
		this.traceId = traceId;
	}
	public YxjBuserWithdrawcashUpper getCashUpper() {
		return cashUpper;
	}
	public void setCashUpper(YxjBuserWithdrawcashUpper cashUpper) {
		this.cashUpper = cashUpper;
	}
	public Date getOperateTime() {
		return operateTime;
	}
	public void setOperateTime(Date operateTime) {
		this.operateTime = operateTime;
	}
	public String getCashState() {
		return cashState;
	}
	public void setCashState(String cashState) {
		this.cashState = cashState;
	}
	public AdminUser getOperator() {
		return operator;
	}
	public void setOperator(AdminUser operator) {
		this.operator = operator;
	}
	public String getRemark() {
		return remark;
	}
	public void setRemark(String remark) {
		this.remark = remark;
	}
	
     
     

}


