package com.youxianji.pojo;
// Generated 2017-3-20 18:53:04 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;

/**
 * YxjBuserWithdrawcashSummation generated by hbm2java
 */
public class YxjBuserWithdrawcashSummation  implements java.io.Serializable {


     private String summationUserid;
     private Integer version;
     private BigDecimal totalCash;
     private BigDecimal frozenAmount;
     
    public YxjBuserWithdrawcashSummation() {
    }

	
    public YxjBuserWithdrawcashSummation(String summationUserid) {
        this.summationUserid = summationUserid;
    }
    public YxjBuserWithdrawcashSummation(String summationUserid, BigDecimal totalCash, BigDecimal frozenAmount) {
       this.summationUserid = summationUserid;
       this.totalCash = totalCash;
       this.frozenAmount = frozenAmount;
    }
   

	public String getSummationUserid() {
        return this.summationUserid;
    }
    
    public void setSummationUserid(String summationUserid) {
        this.summationUserid = summationUserid;
    }
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }
    public BigDecimal getTotalCash() {
        return this.totalCash;
    }
    
    public void setTotalCash(BigDecimal totalCash) {
        this.totalCash = totalCash;
    }
    public BigDecimal getFrozenAmount() {
        return this.frozenAmount;
    }
    
    public void setFrozenAmount(BigDecimal frozenAmount) {
        this.frozenAmount = frozenAmount;
    }




}


