package com.youxianji.pojo;
// Generated 2017-3-20 18:53:04 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;

import com.youxianji.util.CashStateDescMap;



/**
 * YxjBuserWithdrawcashDetail generated by hbm2java
 */
public class YxjBuserWithdrawcashDetail {


     private String cashdetailId;
     private String cashdetailUsername;
     private String cashdetailUserid;
     private Date cashdetailApplydate;
     private String cashdetailState;
     private BigDecimal cashApply;
     private BigDecimal cashFact;
     private String cashdetailTelephone;
     private BigDecimal cashPoundage;
     private String dangerFlag;
     private String returnFlag;
     private YxjBuserWithdrawcashUpper cashUpper;
     
     private String cashdetailStateDesc;
     
	public String getCashdetailId() {
		return cashdetailId;
	}
	public void setCashdetailId(String cashdetailId) {
		this.cashdetailId = cashdetailId;
	}
	public String getCashdetailUsername() {
		return cashdetailUsername;
	}
	public void setCashdetailUsername(String cashdetailUsername) {
		this.cashdetailUsername = cashdetailUsername;
	}
	public String getCashdetailUserid() {
		return cashdetailUserid;
	}
	public void setCashdetailUserid(String cashdetailUserid) {
		this.cashdetailUserid = cashdetailUserid;
	}
	public Date getCashdetailApplydate() {
		return cashdetailApplydate;
	}
	public void setCashdetailApplydate(Date cashdetailApplydate) {
		this.cashdetailApplydate = cashdetailApplydate;
	}
	public String getCashdetailState() {
		return cashdetailState;
	}
	public void setCashdetailState(String cashdetailState) {
		this.cashdetailState = cashdetailState;
	}
	public BigDecimal getCashApply() {
		return cashApply;
	}
	public void setCashApply(BigDecimal cashApply) {
		this.cashApply = cashApply;
	}
	public BigDecimal getCashFact() {
		return cashFact;
	}
	public void setCashFact(BigDecimal cashFact) {
		this.cashFact = cashFact;
	}
	public String getCashdetailTelephone() {
		return cashdetailTelephone;
	}
	public void setCashdetailTelephone(String cashdetailTelephone) {
		this.cashdetailTelephone = cashdetailTelephone;
	}
	public BigDecimal getCashPoundage() {
		return cashPoundage;
	}
	public void setCashPoundage(BigDecimal cashPoundage) {
		this.cashPoundage = cashPoundage;
	}
	public String getDangerFlag() {
		return dangerFlag;
	}
	public void setDangerFlag(String dangerFlag) {
		this.dangerFlag = dangerFlag;
	}
	public String getReturnFlag() {
		return returnFlag;
	}
	public void setReturnFlag(String returnFlag) {
		this.returnFlag = returnFlag;
	}
	
	public YxjBuserWithdrawcashUpper getCashUpper() {
		return cashUpper;
	}
	public void setCashUpper(YxjBuserWithdrawcashUpper cashUpper) {
		this.cashUpper = cashUpper;
	}
	public String getCashdetailStateDesc() {
		return CashStateDescMap.detailStateMap.get(this.cashdetailState);
	}
	public void setCashdetailStateDesc(String cashdetailStateDesc) {
		this.cashdetailStateDesc = cashdetailStateDesc;
	}

    
     
     




}


