package com.youxianji.pojo;
// Generated 2017-3-20 18:53:04 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * YxjBuserWithdrawcashUpper generated by hbm2java
 */
public class YxjBuserWithdrawcashUpper  implements java.io.Serializable {


     private String cashId;
     private UserInfo cashApplyer;
     private Date cashApplytime;
     private BigDecimal cashApply;
     private BigDecimal cashFact;
     private BigDecimal cashPoundage;
     private String cashTelephone;
     private String dangerFlag;
     private String returnFlag;//'退单标识（0：正常，1：退单）',
     private String accountName;
     private String cashState;//'提现状态 0.初始 1.提交成功 2.冻结 3.审核成功 4.已申请报盘 6.回盘成功 7.报盘失败 8.审核失败 9.申请失败 10.申请异常 ',

     
     public String getCashId() {
		return cashId;
	}
	public void setCashId(String cashId) {
		this.cashId = cashId;
	}
	public UserInfo getCashApplyer() {
		return cashApplyer;
	}
	public void setCashApplyer(UserInfo cashApplyer) {
		this.cashApplyer = cashApplyer;
	}
	public Date getCashApplytime() {
		return cashApplytime;
	}
	public void setCashApplytime(Date cashApplytime) {
		this.cashApplytime = cashApplytime;
	}
	public BigDecimal getCashApply() {
		return cashApply;
	}
	public void setCashApply(BigDecimal cashApply) {
		this.cashApply = cashApply;
	}
	public BigDecimal getCashFact() {
		return cashFact;
	}
	public void setCashFact(BigDecimal cashFact) {
		this.cashFact = cashFact;
	}
	public BigDecimal getCashPoundage() {
		return cashPoundage;
	}
	public void setCashPoundage(BigDecimal cashPoundage) {
		this.cashPoundage = cashPoundage;
	}
	public String getCashTelephone() {
		return cashTelephone;
	}
	public void setCashTelephone(String cashTelephone) {
		this.cashTelephone = cashTelephone;
	}
	public String getDangerFlag() {
		return dangerFlag;
	}
	public void setDangerFlag(String dangerFlag) {
		this.dangerFlag = dangerFlag;
	}
	public String getReturnFlag() {
		return returnFlag;
	}
	public void setReturnFlag(String returnFlag) {
		this.returnFlag = returnFlag;
	}
	public String getAccountName() {
		return accountName;
	}
	public void setAccountName(String accountName) {
		this.accountName = accountName;
	}
	public String getCashState() {
		return cashState;
	}
	public void setCashState(String cashState) {
		this.cashState = cashState;
	}

	
}


